# fail2ban filter for Keycloak failed logins
[Definition]
failregex = ^.*"type":"LOGIN_ERROR".*"ipAddress":"<HOST>".*$
            ^.*Login attempt with invalid credentials.*ipAddress=<HOST>.*$
ignoreregex =